using FluentMigrator;
using FluentMigrator.SqlServer;

namespace Ticketing.Migrations.DefaultDB;

[Migration(20240202_1210)]
public class DefaultDB_20240202_1210_InitialData : AutoReversingMigration
{
    public override void Up()
    {
        IfDatabase("PostgreSQL").Execute.Sql(@"
            ALTER TABLE public.""Country"" ALTER COLUMN ""Id"" SET GENERATED BY DEFAULT;
            ALTER TABLE public.""Users"" ALTER COLUMN ""UserId"" SET GENERATED BY DEFAULT;
            ALTER TABLE public.""Roles"" ALTER COLUMN ""RoleId"" SET GENERATED BY DEFAULT;
        ");

        Insert.IntoTable("Country").WithIdentityInsert()
            .Row(new { Id = 1, Name = "Iran" })
            .Row(new { Id = 2, Name = "Italy" })
            .Row(new { Id = 3, Name = "USA" })
            .Row(new { Id = 4, Name = "Brazil" })
            .Row(new { Id = 5, Name = "Australia" })
            .Row(new { Id = 6, Name = "South Africa" });

        Insert.IntoTable("Users").WithIdentityInsert().Row(new
        {
            UserId = 1,
            Username = "admin",
            DisplayName = "admin",
            Email = "moj.jahanbakhsh@gmail.com",
            Source = "site",
            PasswordHash = "Tbx1ar3apCdhYLcYXKqmO5klUr35ehupfPI0pAAsDlesD91YgTwFawmWURhtO7IzJNvtAJx67FYT05uVEtKYGw",
            PasswordSalt = "air_o",
            InsertDate = new DateTime(2024, 1, 1),
            InsertUserId = 1,
            IsActive = 1,
            CountryId = 1
        });

        Insert.IntoTable("Roles").WithIdentityInsert()
            .Row(new { RoleId = 1, RoleName = "Admin" })
            .Row(new { RoleId = 2, RoleName = "Support" })
            .Row(new { RoleId = 3, RoleName = "Develop" })
            .Row(new { RoleId = 4, RoleName = "Supervisor" })
            .Row(new { RoleId = 5, RoleName = "User" });

        Insert.IntoTable("RolePermissions")
            .Row(new { RoleId = 1, PermissionKey = "Ticketing:General" })
            .Row(new { RoleId = 1, PermissionKey = "Ticketing:Ticket:Create" })
            .Row(new { RoleId = 1, PermissionKey = "Ticketing:Ticket:Update" })
            //Only system administrator manages ticketing related actions...
            .Row(new { RoleId = 1, PermissionKey = "Ticketing:Ticket:Admin" })
            .Row(new { RoleId = 1, PermissionKey = "Workflow:View" })
            .Row(new { RoleId = 1, PermissionKey = "Workflow:Modify" })
            .Row(new { RoleId = 1, PermissionKey = "Administration:User" })
            .Row(new { RoleId = 2, PermissionKey = "Ticketing:Ticket:Update" })
            .Row(new { RoleId = 2, PermissionKey = "Workflow:View" })
            .Row(new { RoleId = 3, PermissionKey = "Ticketing:Ticket:Update" })
            .Row(new { RoleId = 3, PermissionKey = "Workflow:View" })
            .Row(new { RoleId = 4, PermissionKey = "Ticketing:Ticket:Update" })
            .Row(new { RoleId = 4, PermissionKey = "Workflow:View" })
            .Row(new { RoleId = 5, PermissionKey = "Ticketing:Ticket:Create" })
            .Row(new { RoleId = 5, PermissionKey = "Workflow:View" });

        IfDatabase("PostgreSQL").Execute.Sql("""
            ALTER TABLE public."Country" ALTER COLUMN "Id" SET GENERATED ALWAYS;
            ALTER TABLE public."Users" ALTER COLUMN "UserId" SET GENERATED ALWAYS;
            ALTER TABLE public."Roles" ALTER COLUMN "RoleId" SET GENERATED ALWAYS;
            SELECT setval('"Country_Id_seq"', (SELECT MAX("Id") FROM "Country"), true);
            SELECT setval('"Users_UserId_seq"', (SELECT MAX("UserId") FROM "Users"), true);
            SELECT setval('"Roles_RoleId_seq"', (SELECT MAX("RoleId") FROM "Roles"), true);
        """);
    }
}