using FluentMigrator;
using FluentMigrator.SqlServer;

namespace Ticketing.Migrations.DefaultDB;

[Migration(20250815_2001)]
public class DefaultDB_20250815_2001_Data : AutoReversingMigration
{
    public override void Up()
    {
        IfDatabase("PostgreSQL").Execute.Sql(@"
            ALTER TABLE ""wf"".""Action"" ALTER COLUMN ""Id"" SET GENERATED BY DEFAULT;
            ALTER TABLE ""wf"".""Status"" ALTER COLUMN ""Id"" SET GENERATED BY DEFAULT;
            ALTER TABLE ""wf"".""Rule"" ALTER COLUMN ""Id"" SET GENERATED BY DEFAULT;
            ALTER TABLE ""tkt"".""Priority"" ALTER COLUMN ""Id"" SET GENERATED BY DEFAULT;
            ALTER TABLE ""tkt"".""System"" ALTER COLUMN ""Id"" SET GENERATED BY DEFAULT;
            ALTER TABLE public.""Users"" ALTER COLUMN ""UserId"" SET GENERATED BY DEFAULT;
        ");

        Insert.IntoTable("Action").InSchema("wf").WithIdentityInsert()
            .Row(new { Id = 1, Name = "Start" })
            .Row(new { Id = 2, Name = "Accept" })
            .Row(new { Id = 3, Name = "Reject" });

        Insert.IntoTable("Status").InSchema("wf")
            .Row(new { Id = 1, Name = "Creating" })
            .Row(new { Id = 2, Name = "Support" })
            .Row(new { Id = 3, Name = "Develop" })
            .Row(new { Id = 4, Name = "Supervise" })
            .Row(new { Id = 5, Name = "Closed" });

        Insert.IntoTable("Rule").InSchema("wf").WithIdentityInsert()
            .Row(new { Id = 1, ActionId = 1, CurrentStatusId = 1, NextStatusId = 2, RoleId = 5, Version = 1, UpdateDate = DateTime.Now })
            .Row(new { Id = 2, ActionId = 2, CurrentStatusId = 2, NextStatusId = 5, RoleId = 2, Version = 1, UpdateDate = DateTime.Now, IsFinalState = true })
            .Row(new { Id = 3, ActionId = 3, CurrentStatusId = 2, NextStatusId = 3, RoleId = 2, Version = 1, UpdateDate = DateTime.Now })
            .Row(new { Id = 4, ActionId = 2, CurrentStatusId = 3, NextStatusId = 4, RoleId = 3, Version = 1, UpdateDate = DateTime.Now, })
            .Row(new { Id = 5, ActionId = 2, CurrentStatusId = 4, NextStatusId = 2, RoleId = 4, Version = 1, UpdateDate = DateTime.Now, })
            .Row(new { Id = 6, ActionId = 3, CurrentStatusId = 4, NextStatusId = 3, RoleId = 4, Version = 1, UpdateDate = DateTime.Now, });

        Insert.IntoTable("Priority").InSchema("tkt").WithIdentityInsert()
            .Row(new { Id = 1, Name = "Normal", Color = "#00ff00", DueTime = 72 })
            .Row(new { Id = 2, Name = "Important", Color = "#ff6600", DueTime = 24 })
            .Row(new { Id = 3, Name = "Urgent", Color = "#ff0000", DueTime = 3 });

        Insert.IntoTable("TimeFlag").InSchema("tkt")
            .Row(new { Name = "The elapsed time is less than half of the problem resolution time.", DuePercent = 50, Color = "#00ff00" })
            .Row(new { Name = "The elapsed time is between 50% and 80% of the total resolution time.", DuePercent = 80, Color = "#ffff00" })
            .Row(new { Name = "The bug fix deadline is approaching.", DuePercent = 100, Color = "#ff6600" })
            .Row(new { Name = "The bug fix window has expired.", DuePercent = 200, Color = "#ff0000" });

        Insert.IntoTable("System").InSchema("tkt").WithIdentityInsert()
            .Row(new { Id = 1, Name = "Post Office Software" })
            .Row(new { Id = 2, Name = "Integrated Exchange Software" });

        Insert.IntoTable("Problem").InSchema("tkt")
            .Row(new { Name = "No connection between the software and the PC POS device", SystemId = 1, PriorityId = 1 })
            .Row(new { Name = "No connection between the software and the barcode printer.", SystemId = 1, PriorityId = 2 })
            .Row(new { Name = "The software version is not being updated.", SystemId = 1, PriorityId = 3 })
            .Row(new { Name = "The rate schedule is not updating", SystemId = 1, PriorityId = 1 })
            .Row(new { Name = "The newly created provincial contract is not transmitted to the post office server.", SystemId = 1, PriorityId = 1 })
            .Row(new { Name = "Request for new server deployment.", SystemId = 2, PriorityId = 1 })
            .Row(new { Name = "Request to relocate the server", SystemId = 2, PriorityId = 1 })
            .Row(new { Name = "Digital registration of the exchange point not received.", SystemId = 2, PriorityId = 1 });

        Insert.IntoTable("Users").WithIdentityInsert()
            .Row(new
            {
                UserId = 2,
                Username = "support1",
                DisplayName = "Iran Support",
                Source = "site",
                PasswordHash = "Tbx1ar3apCdhYLcYXKqmO5klUr35ehupfPI0pAAsDlesD91YgTwFawmWURhtO7IzJNvtAJx67FYT05uVEtKYGw",
                PasswordSalt = "air_o",
                InsertDate = DateTime.Now,
                InsertUserId = 1,
                IsActive = 1,
                CountryId = 1
            })
            .Row(new
            {
                UserId = 3,
                Username = "develop1",
                DisplayName = "Azadpour",
                Source = "site",
                PasswordHash = "Tbx1ar3apCdhYLcYXKqmO5klUr35ehupfPI0pAAsDlesD91YgTwFawmWURhtO7IzJNvtAJx67FYT05uVEtKYGw",
                PasswordSalt = "air_o",
                InsertDate = DateTime.Now,
                InsertUserId = 1,
                IsActive = 1,
                SystemId = 1
            })
            .Row(new
            {
                UserId = 4,
                Username = "supervisor1",
                DisplayName = "Aria Irani",
                Source = "site",
                PasswordHash = "Tbx1ar3apCdhYLcYXKqmO5klUr35ehupfPI0pAAsDlesD91YgTwFawmWURhtO7IzJNvtAJx67FYT05uVEtKYGw",
                PasswordSalt = "air_o",
                InsertDate = DateTime.Now,
                InsertUserId = 1,
                IsActive = 1
            })
            .Row(new
            {
                UserId = 5,
                Username = "user1",
                DisplayName = "John Hong",
                Source = "site",
                PasswordHash = "Tbx1ar3apCdhYLcYXKqmO5klUr35ehupfPI0pAAsDlesD91YgTwFawmWURhtO7IzJNvtAJx67FYT05uVEtKYGw",
                PasswordSalt = "air_o",
                InsertDate = DateTime.Now,
                InsertUserId = 1,
                IsActive = 1
            });

        Insert.IntoTable("UserRoles")
            .Row(new { UserId = 1, RoleId = 1 })
            .Row(new { UserId = 2, RoleId = 2 })
            .Row(new { UserId = 3, RoleId = 3 })
            .Row(new { UserId = 4, RoleId = 4 })
            .Row(new { UserId = 5, RoleId = 5 });

        IfDatabase("PostgreSQL").Execute.Sql("""
            ALTER TABLE "wf"."Action" ALTER COLUMN "Id" SET GENERATED ALWAYS;
            ALTER TABLE "wf"."Status" ALTER COLUMN "Id" SET GENERATED ALWAYS;
            ALTER TABLE "wf"."Rule" ALTER COLUMN "Id" SET GENERATED ALWAYS;
            ALTER TABLE "tkt"."Priority" ALTER COLUMN "Id" SET GENERATED ALWAYS;
            ALTER TABLE "tkt"."System" ALTER COLUMN "Id" SET GENERATED ALWAYS;
            ALTER TABLE public."Users" ALTER COLUMN "UserId" SET GENERATED ALWAYS;

            SELECT setval('wf."Action_Id_seq"', (SELECT MAX("Id") FROM "wf"."Action"), true);
            SELECT setval('wf."Status_Id_seq"', (SELECT MAX("Id") FROM "wf"."Status"), true);
            SELECT setval('wf."Rule_Id_seq"', (SELECT MAX("Id") FROM "wf"."Rule"), true);
            SELECT setval('tkt."Priority_Id_seq"', (SELECT MAX("Id") FROM "tkt"."Priority"), true);
            SELECT setval('tkt."System_Id_seq"', (SELECT MAX("Id") FROM "tkt"."System"), true);
            SELECT setval('"Users_UserId_seq"', (SELECT MAX("UserId") FROM "Users"), true);
        """);
    }
}